### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by lvaleriu** [piegu/language-models#1]
Could you provide please the following files nlputils.py and nlputils2.py?
One of them is here i think: https://github.com/piegu/fastai-projects/blob/master/nlputils2.py

Best,
Valeriu

**Comment by piegu** [comment]
Hi Valeriu.

- nlputils.py is the fastai file in the course NLP repository: https://github.com/fastai/course-nlp/blob/master/nlputils.py

- nlputils2.py is the file I created from nlputils.py to add functions I needed: https://github.com/piegu/fastai-projects/blob/master/nlputils2.py

Best,
Pierre
