### ISSUE TITLE
Liens Drive non fonctionnels

### ISSUE THREAD

**Issue by Ilyas4869** [piegu/language-models#9]
Bonjour,
Merci pour l'article et l'ensemble des ressources fournis.
Les liens pour télécharger les modèles (https://github.com/piegu/language-models/tree/master/models) ne sont pas disponibles, pourriez-vous s'il vous plaît les mettre à jour?

Merci beaucoup d'avance!

**Comment by piegu** [comment]
Bonjour,
Merci pour votre message. Je remarque en effet que les modèles ne sont plus en ligne dans Google Drive. Ils ont sûrement été supprimés par erreur lors d'une mise à jour de dossiers. J'ai donc mis à jour la page github citée en supprimant les liens. Grâce aux notebooks fournis, vous pourrez à nouveau entraîner ces modèles mais j'ai bien conscience que la suppression des modèles en ligne est dommage. Bien à vous.
